name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Test Case 1 [Dave Ghidiu]
      id: test-case-1-dave-ghidiu
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Test Case 1 [Dave Ghidiu]
        setup-command: ''
        command: python3 glue_name.py
        input: |-
          Dave
          Ghidiu
        expected-output: 'Enter first name: Enter last name: Hi, Dave Ghidiu'
        comparison-method: contains
        timeout: 10
        max-score: 5
    - name: Test Case 2 [bart simpson]
      id: test-case-2-bart-simpson
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Test Case 2 [bart simpson]
        setup-command: ''
        command: python3 glue_name.py
        input: |-
          bart
          simpson
        expected-output: 'Enter first name: Enter last name: Hi, bart simpson

          '
        comparison-method: exact
        timeout: 10
        max-score: 5
    - name: Test Case 3 [Paige LaBarr]
      id: test-case-3-paige-labarr
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Test Case 3 [Paige LaBarr]
        setup-command: ''
        command: python3 glue_name.py
        input: |-
          Paige
          LaBarr
        expected-output: 'Enter first name: Enter last name: Hi, Paige LaBarr'
        comparison-method: exact
        timeout: 10
        max-score: 5
    - name: Test Case 4 [Lisa Simpson, esquire]
      id: test-case-4-lisa-simpson-esquire
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Test Case 4 [Lisa Simpson, esquire]
        setup-command: ''
        command: python3 glue_name.py
        input: |-
          Lisa
          Simpson, esquire
        expected-output: 'Enter first name: Enter last name: Hi, Lisa Simpson, esquire

          '
        comparison-method: exact
        timeout: 10
        max-score: 5
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST-CASE-1-DAVE-GHIDIU_RESULTS: "${{steps.test-case-1-dave-ghidiu.outputs.result}}"
        TEST-CASE-2-BART-SIMPSON_RESULTS: "${{steps.test-case-2-bart-simpson.outputs.result}}"
        TEST-CASE-3-PAIGE-LABARR_RESULTS: "${{steps.test-case-3-paige-labarr.outputs.result}}"
        TEST-CASE-4-LISA-SIMPSON-ESQUIRE_RESULTS: "${{steps.test-case-4-lisa-simpson-esquire.outputs.result}}"
      with:
        runners: test-case-1-dave-ghidiu,test-case-2-bart-simpson,test-case-3-paige-labarr,test-case-4-lisa-simpson-esquire
